### ISSUE TITLE
single word not translated

### ISSUE THREAD

**Issue by maheDJ** [damienvanrobaeys/About_my_device#11]
In the "Details" tab, in the "Last Update" line if Antispyware and Antivirus is up to date it says "Antispyware **et** Antivirus up to date".
Should be "and" instead ot "et" I guess :)

**Comment by damienvanrobaeys** [comment]
Thanks for the feedback.
It will be resolved in the next version

**Comment by maheDJ** [comment]
I don't want to open a new issue, I've discovered another phrase which isn't translated to English.
In "About_this_computer.xaml" => "Rafraichir l'affichage des écrans"
Should be line 143.
